version: '3.0'
services:
  nginx:
    depends_on:
      - server
      - frontend
    restart: always
    build:  "./Nginx"
    ports:
      - "80:90"

  server:
    build: "./Backend"
    restart: always
    container_name: "server"
    ports: 
      - "3000:3000"
  frontend:
    build: "./Frontend"
    restart: always
    container_name: "frontend"
    ports:
      - "8080:8080"
    links:
      - server
  