version: '3.0'
services:
  nginx:
    depends_on:
      - server
      - frontend
    restart: always
    build:  "./Nginx"
    ports:
      - "3050:80"

  server:
    build: "./Backend"
    container_name: "server"
    ports: 
      - "3000:3000"
  frontend:
    build: "./Frontend"
    container_name: "frontend"
    ports:
      - "8080:8080"
  